---
# Add a fast check to speed reconfiguration
- name: Stat /opt/hadoop
  ansible.builtin.stat:
    path=/opt/hadoop
  register: hadoop_installed

- name: Include install.yml
  ansible.builtin.import_tasks: install.yml
  when: not hadoop_installed.stat.exists

- name: Include configure.yml
  ansible.builtin.import_tasks: configure.yml

- name: Include configure_users
  ansible.builtin.import_tasks: configure_users.yml
  when: users_dict.values()
