- name: stop hadoop-dfs
  ansible.builtin.action: shell {{ hadoop_home }}/bin/hdfs --daemon stop namenode
  when: ( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'namenode' )
  listen: "restart hadoop-dfs"
  ignore_errors:  yes

- name: start hadoop-dfs
  ansible.builtin.action: shell {{ hadoop_home }}/bin/hdfs --daemon start namenode
  when: ( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'namenode' )
  listen: "restart hadoop-dfs"

- name: stop yarn-resourcemanager
  ansible.builtin.action: shell {{ hadoop_home }}/bin/yarn --daemon stop resourcemanager
  when: ( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'resourcemanager' )
  listen: "restart yarn-resourcemanager"
  ignore_errors:  yes

- name: start yarn-resourcemanager
  ansible.builtin.action: shell {{ hadoop_home }}/bin/yarn --daemon start resourcemanager
  when: ( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'resourcemanager' )
  listen: "restart yarn-resourcemanager"

- name: stop hadoop-datanode
  ansible.builtin.action: shell {{ hadoop_home }}/bin/hdfs --daemon stop datanode
  when: ( hadoop_type_of_node == 'slave' ) or ( hadoop_type_of_node == 'datanode' )
  listen: "restart hadoop-datanode"
  ignore_errors:  yes

- name: start hadoop-datanode
  ansible.builtin.action: shell {{ hadoop_home }}/bin/hdfs --daemon start datanode
  when: ( hadoop_type_of_node == 'slave' ) or ( hadoop_type_of_node == 'datanode' )
  listen: "restart hadoop-datanode"

- name: stop yarn-nodemanager
  ansible.builtin.action: shell {{ hadoop_home }}/bin/yarn --daemon stop nodemanager
  when: ( hadoop_type_of_node == 'slave' ) or ( hadoop_type_of_node == 'nodemanager' )
  listen: "restart yarn-nodemanager"
  ignore_errors:  yes

- name: start yarn-nodemanager
  ansible.builtin.action: shell {{ hadoop_home }}/bin/yarn --daemon start nodemanager
  when: ( hadoop_type_of_node == 'slave' ) or ( hadoop_type_of_node == 'nodemanager' )
  listen: "restart yarn-nodemanager"

- name: refreshDFSNodes
  ansible.builtin.command: "{{ hadoop_home }}/bin/hdfs dfsadmin -refreshNodes"
  when: ( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'namenode' )
  ignore_errors: yes

- name: refreshYarnNodes
  ansible.builtin.command: "{{ hadoop_home }}/bin/yarn rmadmin -refreshNodes"
  when: ( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'resourcemanager' )
  ignore_errors: yes
